[package]
name = "flang-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
flang = { version = "0.1", path = "../" } 
colored = "2"
rustyline = "5.0.3"
clap = {version = "4.4", features = ["derive"]}

[profile.release]
strip = true
lto = true
panic = "abort"
