name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: v0.1 tests
      run: cargo run --bin test tests/v0.1.json
    - name: stdlib tests
      run: cargo run --bin test tests/stdlib.json
